# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-24 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserInfo', '0001_initial'),
        ('catalogue', '0015_auto_20171007_0901'),
        ('ProductInfo', '0004_auto_20180204_0244'),
        ('basket', '0007_slugfield_noop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(2, '\u5df2\u786e\u8ba4'), (1, '\u5f85\u786e\u8ba4')], verbose_name='\u72b6\u6001')),
                ('server_money', models.FloatField(verbose_name='\u670d\u52a1\u8d39')),
                ('total_money', models.FloatField(verbose_name='\u603b\u4ef7')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmOrderInfo', to='basket.Basket', verbose_name='\u5173\u8054\u8d2d\u7269\u8f66\u4fe1\u606f')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmOrderInfo', to='UserInfo.RoleInfo', verbose_name='\u4e70\u624b')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmOrderInfo', to='ProductInfo.ProductOwner', verbose_name='\u4f9b\u5e94\u5546')),
            ],
        ),
        migrations.CreateModel(
            name='confirmProductRelathionship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmOrderInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='senderConfirmInfo.ConfirmOrderInfo', verbose_name=b'products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.Product', verbose_name='\u4ea7\u54c1')),
            ],
        ),
    ]
