# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-24 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senderConfirmInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmorderinfo',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmOrderInfo', to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u624b'),
        ),
        migrations.AlterField(
            model_name='confirmorderinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmOrderInfo', to='ProductInfo.ProductOwner', verbose_name='\u4f9b\u5e94\u5546'),
        ),
    ]
