# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.CreateModel(
            name='subProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subProduct', to='catalogue.Product', verbose_name='\u4e0b\u7ea7\u4ea7\u54c1')),
            ],
        ),
    ]
