# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductInfo', '0002_auto_20171002_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productowner',
            old_name='parentProduct',
            new_name='product',
        ),
    ]
