# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-04 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductInfo', '0003_auto_20171003_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productowner',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='catalogue.Product', verbose_name='\u4ea7\u54c1'),
        ),
    ]
