# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(2, '\u9001\u8d27\u4eba'), (3, '\u5ba2\u6237'), (1, '\u4e70\u624b')], verbose_name='\u89d2\u8272')),
                ('app_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='app_key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
    ]
